name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KNOWN_ISSUES: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Setup API database
      run: |
        cd apps/api
        pnpm prisma generate
        pnpm prisma db push
        pnpm run seed

    - name: Build applications
      run: pnpm build

    - name: Run API tests
      run: pnpm test:api

    - name: Install Playwright browsers
      run: |
        cd apps/web
        pnpm exec playwright install --with-deps chromium

    - name: Run E2E tests
      run: pnpm test:ui

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: apps/web/playwright-report/
        retention-days: 30
